language: node_js
node_js:
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "4"
  - "iojs"

compiler: gcc
sudo: false

os:
  - linux
  - osx

env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true

matrix:
  fast_finish: true
  exclude:
    - node_js: iojs
    - node_js: "0.10"
      os: osx
    - node_js: "0.12"
      os: osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
      - gcc-4.9
      - g++-4.9

before_install:
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      if (( $(node -v | sed 's/v//' | sed 's/\..*$//') > 9 )); then
        export CC="gcc-4.9";
        export CXX="g++-4.9";
        export LINK="gcc-4.9";
        export LINKXX="g++-4.9";
      else
        export CC="gcc-4.7";
        export CXX="g++-4.7";
        export LINK="gcc-4.7";
        export LINKXX="g++-4.7";
      fi
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

script:
  - npm install
  - npm test

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
